services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
